### ISSUE TITLE
extensions/Browser_Info_and_Language.js is the ST's Browser Stuff extension

### ISSUE THREAD

**Issue by savaka2** [Thepuzzlegame/Thepuzzlegame.github.io#6]
As seen here: https://github.com/Thepuzzlegame/Thepuzzlegame.github.io/blob/master/extensions/Browser_Info_and_Language.js

**Comment by Thepuzzlegame** [comment]
Nice catch! Changing the author.

**Comment by savaka2** [comment]
I don't think you entirely got this. The author was right. The whole listing on the directory including the link was right. The only thing wrong is the code in the file, which is exactly the same as the ST's Browser Stuff extension. Notice that these two files have identical contents:
https://github.com/sayamindu/scratch-extensions/blob/gh-pages/browser_extension.js
https://github.com/Thepuzzlegame/Thepuzzlegame.github.io/blob/master/extensions/Browser_Info_and_Language.js

**Comment by Thepuzzlegame** [comment]
What's wrong with the code? Are you saying the comment at the beginning doesn't belong?

**Comment by savaka2** [comment]
The whole contents of the file Browser_Info_and_Language.js is not actually andrewjcole's Browser Info and Language extension. It is identical to the ST's Browser Stuff. I fixed this on my extensions directory. The correct contents can be found here: http://andrewjcole.weebly.com/uploads/8/0/9/8/8098232/browser-info-and-language.js

**Comment by Thepuzzlegame** [comment]
Ah, I see.
