### ISSUE TITLE
Weather extension by mxsscott doesn't work

### ISSUE THREAD

**Issue by savaka2** [Thepuzzlegame/Thepuzzlegame.github.io#9]
The website mscott.cx does not seem to exist. The extension can be found here but it is not on a GitHub Page: https://github.com/mxsscott/scratchext/blob/master/exts/weather.js

**Comment by Thepuzzlegame** [comment]
Hmm, not sure I understand the issue...

**Comment by savaka2** [comment]
Never mind, it's my school's weird web filter
